### ISSUE TITLE
reducePromiseActions

### ISSUE THREAD

**Issue by ashl1** [w33ble/redux-promise-actions#2]
Hello, Joe!
Thanks for the plugin!
For our purpose we need to reduce promise actions like one single promise action. I'm looking on some handlePromiseActions reducer with reduceReducers(). This requirement comes from sophisticated dependencies in the promise actions we need to watch on.
What do you need about PR with the following code, for example. Or you prefer seperated module?

```javascript
import {
    handlePromiseAction,
    isLoading,
    isRejected,
    isResolved
} from 'redux-promise-actions'
import reduceReducers from 'reduce-reducers'

export default const reducePromiseActions = (actions, initial) => reduceReducers(
    handlePromiseAction(
        actions[0],
        (state, action) => isLoading(action) ? 'loading' : state,
        initial
    ),
    ...actions.map(action =>
        handlePromiseAction(
            action,
            (state, action) => isRejected(action) ? 'rejected' : state,
            initial
        )
    ),
    handlePromiseAction(
        actions[actions.length - 1],
        (state, action) => isResolved(action) ? 'resolved' : state,
        initial
    )
)

```

**Comment by w33ble** [comment]
I'm curious about the use case. Can you show me an example of this in use? It'd help me understand why it's helpful to have. 

I was thinking about adding a plural `handlePromiseActions`, similar to [handleActions in redux-actions](https://redux-actions.js.org/docs/api/handleAction.html), but hadn't considered adding something like this. At first glance, it seems like a pretty specific use case, worth of its own module, but perhaps I'm just missing the value here.

**Comment by ashl1** [comment]
You might be right about separate module - this is e\what I asked about.
The use case is simple. As I mentioned before I use several promised actions. They make requests to the server. Because the data from some of them is used I provide separated reducers for the actions. On the other hand I should provide notification to the user about that actions. But not about each of them, I provide grouped state like "Loading...", "Making global action...".
For example, for "Loading" we do the actions:
```javascript
promisedAction1 {
  await dispatch(inner1Action1)
  await Promise.all([inner1Action2, inner1Action3])
}
promisedAction2 {
...
}
await Promise.all([promisedAction1, promisedAction2])
```
I also have another background tasks (which does';t require the notificaiton) but uses the same actions like:
```javascript
dispatch(innerAction1)
```

The "notification" purpose should follow rules:
- If any of them fails we will stop notification. 
- If all of them successfully finished we will stop the notification (in the code above it will finish if only last is finished)
- The notification should be started only if first is started
- The notification is not an action. It is a react to actions.

**Comment by w33ble** [comment]
I thought a little about how I'd implement this, and basically I think I'd treat all of these "coupled actions" as their own action, with their own reducer. The reducer would be in charge of handling the notification state. 

Basically, if you dispatch `promisedAction1`, you can mix the notification logic to just that "coupled action", and the fact that it uses other actions internally, or that those actions can be used on their own, is just an implementation detail. Maybe I'm wrong, I'll admit that I think I sometimes use redux incorrectly, but that's how I'd do it.

With that in mind, I don't think this really requires specific module code to perform. Maybe you can wrap it up more conveniently with a module, but I'm pretty certain `redux-promise-actions` isn't the right place for that. 

Does that sound right to you, or am I still missing something?

**Comment by ashl1** [comment]
Ok. If needed I'll make another lib.
Yes. The grouping actions with another aciton is what I use too but it might be sophisticated in parallel.

**Comment by ashl1** [comment]
The library is published in https://github.com/ashl1/notify-promise-actions
