### ISSUE TITLE
react-app-rewired build

### ISSUE THREAD

**Issue by gokul-toobler** [w33ble/redux-promise-actions#3]
Failed to minify the code from this file:

        ./node_modules/redux-promise-actions/index.js:6

issue when taking buid using 'react-app-rewired build'

**Comment by w33ble** [comment]
I’m not planning to continue maintaining this library. Note that the status in the readme is deprecated. Are you interested in maintaining it? If not, you’ll probably want to use another Redux helper.

**Comment by gokul-toobler** [comment]
ok
